//! Brand splash — figlet wordmark + Braille logo + framed inventory pane.
//!
//! Rendered at the top of `rantaiclaw agent` and `rantaiclaw setup` so every
//! interactive entry point reads as one product. Matches the rantai-agents
//! web palette:
//!
//! * sky    `#5eb8ff` — logo squares, banner top row
//! * blue   `#3b8cff` — primary brand accent (oklch(0.55 0.2 250))
//! * navy   `#040b2e` — logo body, frame
//! * muted  `#6b7280` — secondary text
//!
//! ## Layout adapts to terminal width
//!
//! * `cols >= 80`: wide layout — banner above, framed pane with logo on the
//!   left and inventory on the right. Uses `banner_full.txt`.
//! * `cols >= 60`: medium layout — same wide split with the smaller
//!   `banner_small.txt` wordmark.
//! * `cols <  60`: compact layout — single icon line + title, no frame, no
//!   logo pane.
//!
//! ## Assets
//!
//! Generated by `scripts/branding/render_logo_ascii.py` against
//! `Logo-only Border or Stroke (1).png`. Pillow + pyfiglet are only needed
//! when regenerating; production builds bake the assets via `include_str!`.
//!
//! ## NO_COLOR
//!
//! `NO_COLOR=1` short-circuits all 24-bit truecolor escapes and swaps the
//! Braille logo for a `░▒▓█` density fallback. The frame and layout stay
//! intact.

use std::fmt::Write as _;

const BANNER_FULL: &str = include_str!("assets/banner_full.txt");
const BANNER_SMALL: &str = include_str!("assets/banner_small.txt");
const LOGO_GRADIENT: &str = include_str!("assets/logo_braille_gradient.txt");
const LOGO_PLAIN: &str = include_str!("assets/logo_plain.txt");

const FRAME_LIGHT: char = '─';
const FRAME_TL: char = '╭';
const FRAME_TR: char = '╮';
const FRAME_BL: char = '╰';
const FRAME_BR: char = '╯';
const FRAME_VR: char = '│';

/// 4-color palette indexed by the `@N@` row tags in
/// `logo_braille_gradient.txt` and by the per-row gradient on the figlet
/// banner: 0 = sky, 1 = blue, 2 = navy-bright, 3 = muted.
const PALETTE: [(u8, u8, u8); 4] = [
    (94, 184, 255),  // sky      #5eb8ff
    (59, 140, 255),  // blue     #3b8cff
    (40, 70, 140),   // navy-br  brightened so it's readable on dark bg
    (107, 114, 128), // muted    #6b7280
];

/// Banner gradient — same indexing as `PALETTE`. Length tied to the figlet
/// font's row count; we cycle modulo banner length so any font fits.
const BANNER_GRADIENT: [usize; 6] = [0, 0, 1, 1, 2, 3];

fn no_color() -> bool {
    std::env::var_os("NO_COLOR").is_some()
}

fn fg(idx: usize) -> String {
    if no_color() {
        return String::new();
    }
    let (r, g, b) = PALETTE[idx.min(PALETTE.len() - 1)];
    format!("\x1b[38;2;{r};{g};{b}m")
}

fn bold() -> &'static str {
    if no_color() {
        ""
    } else {
        "\x1b[1m"
    }
}

fn dim() -> &'static str {
    if no_color() {
        ""
    } else {
        "\x1b[2m"
    }
}

fn reset() -> &'static str {
    if no_color() {
        ""
    } else {
        "\x1b[0m"
    }
}

/// Visible width of a string after stripping ANSI CSI sequences. Treats every
/// non-escape character as 1 column wide, which matches our Braille and
/// half-block usage (figlet line-art glyphs are also single-width).
pub(crate) fn visible_width(s: &str) -> usize {
    let mut w = 0;
    let mut in_esc = false;
    for ch in s.chars() {
        if in_esc {
            if ch.is_ascii_alphabetic() {
                in_esc = false;
            }
            continue;
        }
        if ch == '\x1b' {
            in_esc = true;
            continue;
        }
        w += 1;
    }
    w
}

fn pad_visible(s: &str, target: usize) -> String {
    let w = visible_width(s);
    if w >= target {
        s.to_string()
    } else {
        format!("{s}{}", " ".repeat(target - w))
    }
}

/// Pick a banner asset that fits in `cols`. Returns `(banner_lines, width)`.
fn choose_banner(cols: u16) -> Option<(Vec<&'static str>, usize)> {
    fn fits(text: &str, cols: u16) -> Option<(Vec<&str>, usize)> {
        let lines: Vec<&str> = text.lines().collect();
        let max_w = lines.iter().map(|l| l.chars().count()).max().unwrap_or(0);
        if max_w <= cols as usize {
            Some((lines, max_w))
        } else {
            None
        }
    }
    fits(BANNER_FULL, cols).or_else(|| fits(BANNER_SMALL, cols))
}

/// Render the wordmark with a per-row gradient color.
fn render_banner(banner_lines: &[&str]) -> String {
    let mut out = String::new();
    for (i, line) in banner_lines.iter().enumerate() {
        let color_idx = BANNER_GRADIENT[i % BANNER_GRADIENT.len()];
        let _ = writeln!(out, "{}{}{}{}", bold(), fg(color_idx), line, reset());
    }
    out
}

/// Parse the gradient file into colored Braille rows. Each line of the
/// asset is `@N@\t<glyphs>` — N indexes `PALETTE`. NO_COLOR strips the
/// color but keeps the glyphs.
fn render_logo() -> Vec<String> {
    if no_color() {
        return LOGO_PLAIN.lines().map(str::to_string).collect();
    }
    LOGO_GRADIENT
        .lines()
        .map(|raw| {
            // Tag form: `@N@\t<glyphs>` — fall back to plain if malformed.
            if let Some(rest) = raw.strip_prefix('@') {
                if let Some((idx_s, glyphs)) = rest.split_once("@\t") {
                    if let Ok(idx) = idx_s.parse::<usize>() {
                        return format!("{}{}{}", fg(idx), glyphs, reset());
                    }
                }
            }
            raw.to_string()
        })
        .collect()
}

/// One pane of inventory on the right side of the splash.
#[derive(Debug, Clone)]
pub struct Inventory<'a> {
    pub title: &'a str,
    pub subtitle: Option<&'a str>,
    pub tools: &'a [(&'a str, &'a [&'a str])],
    pub skills: &'a [(&'a str, &'a [&'a str])],
    pub footer: Option<&'a str>,
}

impl<'a> Inventory<'a> {
    pub fn minimal(title: &'a str, subtitle: Option<&'a str>) -> Self {
        Self {
            title,
            subtitle,
            tools: &[],
            skills: &[],
            footer: None,
        }
    }
}

/// Truncate a comma-joined list to `budget` *visible* columns, appending
/// `…+N` if items had to be dropped. Mirrors Hermes' `truncLine` helper.
fn truncate_items(items: &[&str], budget: usize) -> String {
    let mut out = String::new();
    let mut shown = 0usize;
    for item in items {
        let next = if out.is_empty() {
            item.to_string()
        } else {
            format!("{out}, {item}")
        };
        if next.chars().count() > budget {
            return if out.is_empty() {
                format!("{}, …", item)
            } else {
                format!("{out}, …+{}", items.len() - shown)
            };
        }
        out = next;
        shown += 1;
    }
    out
}

fn render_inventory_lines(inv: &Inventory<'_>, budget: usize) -> Vec<String> {
    let mut lines: Vec<String> = Vec::new();
    let title_style = format!("{}{}", bold(), fg(1));
    let sub_style = dim();
    let cat_style = fg(0);
    let r = reset();

    let mut header = format!("{title_style}{}{r}", inv.title);
    if let Some(sub) = inv.subtitle {
        header.push_str(&format!(" {sub_style}· {sub}{r}"));
    }
    lines.push(header);

    if !inv.tools.is_empty() {
        lines.push(String::new());
        lines.push(format!("{title_style}Available Tools{r}"));
        for (cat, items) in inv.tools {
            let label = format!("{cat}: ");
            let value = truncate_items(items, budget.saturating_sub(label.chars().count()));
            lines.push(format!("{cat_style}{label}{r}{value}"));
        }
    }

    if !inv.skills.is_empty() {
        lines.push(String::new());
        lines.push(format!("{title_style}Available Skills{r}"));
        for (cat, items) in inv.skills {
            let label = format!("{cat}: ");
            let value = truncate_items(items, budget.saturating_sub(label.chars().count()));
            lines.push(format!("{cat_style}{label}{r}{value}"));
        }
    }

    if let Some(footer) = inv.footer {
        lines.push(String::new());
        lines.push(format!("{sub_style}{footer}{r}"));
    }

    lines
}

/// Detected terminal columns; falls back to 100 when unknown so we still
/// produce a visually correct splash in pipes / non-TTY contexts.
fn term_cols() -> u16 {
    console::Term::stdout()
        .size_checked()
        .map(|(_rows, cols)| cols)
        .unwrap_or(100)
}

/// Compose the full splash. Adapts to terminal width:
/// * cols ≥ 80 → wide framed splash with logo on left, inventory on right
/// * cols < 60 → single-line `▎ Rantaiclaw v…` banner only (no frame)
pub fn render_splash(inv: &Inventory<'_>) -> String {
    render_splash_at_width(inv, term_cols())
}

/// Test seam — same as `render_splash` but with explicit terminal width.
pub fn render_splash_at_width(inv: &Inventory<'_>, cols: u16) -> String {
    let frame = fg(2);
    let r = reset();

    // Compact layout: too narrow for a frame.
    if cols < 60 {
        let mut out = String::new();
        out.push('\n');
        let _ = writeln!(out, "{}{}▎ {}{}", bold(), fg(0), inv.title, r,);
        if let Some(sub) = inv.subtitle {
            let _ = writeln!(out, "  {}{}{}", dim(), sub, r);
        }
        if let Some(footer) = inv.footer {
            let _ = writeln!(out, "  {}{}{}", dim(), footer, r);
        }
        out.push('\n');
        return out;
    }

    // Wide / medium layout.
    let banner_section = match choose_banner(cols) {
        Some((lines, _w)) => render_banner(&lines),
        None => String::new(),
    };

    let logo = render_logo();
    let logo_pane_w = 32; // 30 char glyphs + 2 padding
    let frame_w = (cols as usize).min(100);
    // 2 verticals + 1 separator-vertical + logo pane + right pane = frame_w
    let right_pane_w = frame_w.saturating_sub(logo_pane_w + 3).max(20);

    let inv_lines = render_inventory_lines(inv, right_pane_w.saturating_sub(2));
    let pane_height = logo.len().max(inv_lines.len()).max(8);

    let dash = FRAME_LIGHT.to_string();
    let top = format!(
        "{frame}{FRAME_TL}{}{FRAME_TR}{r}",
        dash.repeat(frame_w.saturating_sub(2)),
    );
    let bottom = format!(
        "{frame}{FRAME_BL}{}{FRAME_BR}{r}",
        dash.repeat(frame_w.saturating_sub(2)),
    );

    let mut out = String::new();
    out.push('\n');
    out.push_str(&banner_section);
    out.push('\n');
    out.push_str(&top);
    out.push('\n');
    for i in 0..pane_height {
        let left = logo.get(i).cloned().unwrap_or_default();
        let right = inv_lines.get(i).cloned().unwrap_or_default();
        let left_padded = pad_visible(&left, logo_pane_w);
        let right_padded = pad_visible(&right, right_pane_w.saturating_sub(1));
        let _ = writeln!(
            out,
            "{frame}{FRAME_VR}{r} {left_padded} {frame}{FRAME_VR}{r} {right_padded}{frame}{FRAME_VR}{r}",
        );
    }
    out.push_str(&bottom);
    out.push('\n');
    out
}

/// Banner only — used by short-lived commands that just want the brand
/// presence without the full inventory pane.
pub fn render_banner_only() -> String {
    let cols = term_cols();
    let banner = choose_banner(cols)
        .map(|(lines, _)| render_banner(&lines))
        .unwrap_or_else(|| format!("{}{}▎ Rantaiclaw{}\n", bold(), fg(0), reset()));
    format!("\n{}", banner)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn banner_full_fits_in_82_cols() {
        // ANSI Shadow at width=200 produces a single-row "RANTAICLAW" at
        // exactly 80 cols. Allow a 2-col cushion for edge cases.
        let max = BANNER_FULL
            .lines()
            .map(|l| l.chars().count())
            .max()
            .unwrap();
        assert!(max <= 82, "banner_full max line is {max} chars");
    }

    #[test]
    fn banner_small_fits_in_60_cols() {
        let max = BANNER_SMALL
            .lines()
            .map(|l| l.chars().count())
            .max()
            .unwrap();
        assert!(max <= 60, "banner_small max line is {max} chars");
    }

    #[test]
    fn logo_braille_is_30_chars_wide() {
        let widths: Vec<usize> = LOGO_GRADIENT
            .lines()
            .filter_map(|l| l.split_once('\t').map(|(_, body)| body.chars().count()))
            .collect();
        for w in &widths {
            assert_eq!(*w, 30, "row width is {w}, expected 30");
        }
        assert_eq!(widths.len(), 16);
    }

    #[test]
    fn wide_splash_uses_frame() {
        let inv = Inventory::minimal("Rantaiclaw v0.5.0", Some("test"));
        let s = render_splash_at_width(&inv, 100);
        assert!(
            s.contains('╭'),
            "wide splash should have rounded frame: {s:?}"
        );
        assert!(s.contains('╯'));
    }

    #[test]
    fn compact_splash_skips_frame_under_60_cols() {
        let inv = Inventory::minimal("Rantaiclaw v0.5.0", Some("test"));
        let s = render_splash_at_width(&inv, 50);
        assert!(!s.contains('╭'), "compact splash should NOT have a frame");
        assert!(s.contains("Rantaiclaw"));
    }

    #[test]
    fn no_color_disables_escapes() {
        let prev = std::env::var_os("NO_COLOR");
        std::env::set_var("NO_COLOR", "1");
        let inv = Inventory::minimal("Rantaiclaw", None);
        let s = render_splash_at_width(&inv, 100);
        match prev {
            Some(v) => std::env::set_var("NO_COLOR", v),
            None => std::env::remove_var("NO_COLOR"),
        }
        assert!(!s.contains("\x1b["), "NO_COLOR splash had ANSI: {s:?}");
    }

    #[test]
    fn truncate_appends_overflow_marker() {
        let items: Vec<&str> = vec!["alpha", "beta", "gamma", "delta"];
        let r = truncate_items(&items, 12);
        assert!(r.ends_with("…+2") || r.ends_with(", …"), "got {r:?}");
    }

    #[test]
    fn truncate_keeps_full_list_when_fits() {
        let items: Vec<&str> = vec!["a", "b", "c"];
        let r = truncate_items(&items, 64);
        assert_eq!(r, "a, b, c");
    }

    #[test]
    fn visible_width_strips_ansi() {
        assert_eq!(visible_width("\x1b[31mhello\x1b[0m"), 5);
    }
}
