//! Opt-in query expansion — port of `src/lib/rag/query-expansion.ts`.
//!
//! Fires a single OpenRouter chat completion requesting N paraphrases of the
//! user's question, returns `[original, ...paraphrases]` dedeuped case- and
//! whitespace-insensitively. Fail-soft: any error path returns `[query]`.
//!
//! A 1h LRU keyed on the trimmed query memoizes successful expansions
//! per-process. Failed calls aren't cached so the next retry has a fresh shot.

use std::sync::OnceLock;
use std::time::Duration;

use tokio::sync::Mutex;

use crate::kb::embed::cache::LruCache;
use crate::kb::KbConfig;

const CACHE_TTL: Duration = Duration::from_secs(60 * 60); // 1h, matches TS source
const CACHE_CAP: usize = 1024;
const TIMEOUT: Duration = Duration::from_secs(8);

/// Per-process cache. Wrapped in `OnceLock` so initialization is deferred
/// until the first call — keeps non-KB binaries from paying the allocation.
fn cache() -> &'static Mutex<LruCache<String, Vec<String>>> {
    static CACHE: OnceLock<Mutex<LruCache<String, Vec<String>>>> = OnceLock::new();
    CACHE.get_or_init(|| Mutex::new(LruCache::new(CACHE_CAP, Some(CACHE_TTL))))
}

/// Expand `query` into `[original, ...paraphrases]`.
///
/// Returns `[query]` when:
/// - `cfg.query_expansion_enabled` is false
/// - `OPENROUTER_API_KEY` is unset
/// - the LLM call fails (network, non-2xx, parse error)
/// - the response can't be parsed as a JSON array of strings
///
/// Never throws — degrades gracefully to baseline retrieval.
pub async fn expand_query(cfg: &KbConfig, query: &str) -> Vec<String> {
    let q = query.trim();
    if q.is_empty() {
        return Vec::new();
    }
    if !cfg.query_expansion_enabled {
        return vec![q.to_string()];
    }

    let api_key = std::env::var("OPENROUTER_API_KEY").unwrap_or_default();
    if api_key.is_empty() {
        return vec![q.to_string()];
    }

    // Cache lookup. Hold the lock only across the lookup itself — releasing
    // before the HTTP call lets concurrent retrievals share the same cache.
    //
    // Key includes the model name so swapping
    // `KB_QUERY_EXPANSION_MODEL` (e.g. between requests in tests, or via
    // dynamic config) does NOT return paraphrases generated by the old model.
    let cache_key = format!("{}::{q}", cfg.query_expansion_model);
    if let Some(hit) = cache().lock().await.get(&cache_key) {
        return hit;
    }

    let prompt = format!(
        "Generate exactly {} alternative phrasings of the following user question, optimized for semantic search over a knowledge base. Each paraphrase MUST preserve the original intent but vary wording, synonyms, or perspective. Output ONLY a JSON array of {} strings. No prose, no markdown fences.\n\nQuestion: {}",
        cfg.query_expansion_paraphrases, cfg.query_expansion_paraphrases, q
    );

    let body = serde_json::json!({
        "model": cfg.query_expansion_model,
        "messages": [{ "role": "user", "content": prompt }],
        "max_tokens": 300,
        "temperature": 0.3,
    });

    let (paraphrases, success) =
        match fetch_paraphrases(&cfg.openrouter_chat_url, &api_key, &body).await {
            Ok(p) => (p, true),
            Err(e) => {
                tracing::warn!(
                    target: "kb::retrieve::query_expansion",
                    error = %e,
                    "expansion failed; using original query only",
                );
                (Vec::new(), false)
            }
        };

    // Dedupe paraphrases against the original. Case- and whitespace-insensitive
    // match (`Foo  bar` collides with `foo bar`) — keep original casing in
    // output, matching the TS source.
    let norm = |s: &str| s.to_lowercase().split_whitespace().collect::<Vec<_>>().join(" ");
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
    seen.insert(norm(q));
    let mut cleaned = vec![q.to_string()];
    for p in paraphrases {
        let trimmed = p.trim();
        if trimmed.is_empty() {
            continue;
        }
        let key = norm(trimmed);
        if seen.insert(key) {
            cleaned.push(trimmed.to_string());
        }
    }

    if success {
        // Cache only successful calls — failures retry on next call.
        cache().lock().await.put(cache_key, cleaned.clone());
    }
    cleaned
}

/// POST to OpenRouter and parse the JSON-array response. Errors propagate so
/// the caller can decide whether to cache.
async fn fetch_paraphrases(
    url: &str,
    api_key: &str,
    body: &serde_json::Value,
) -> Result<Vec<String>, String> {
    let client = reqwest::Client::builder()
        .timeout(TIMEOUT)
        .build()
        .map_err(|e| format!("client build: {e}"))?;
    let resp = client
        .post(url)
        .bearer_auth(api_key)
        .json(body)
        .send()
        .await
        .map_err(|e| format!("send: {e}"))?;
    if !resp.status().is_success() {
        return Err(format!("expansion {}", resp.status().as_u16()));
    }
    let data: serde_json::Value =
        resp.json().await.map_err(|e| format!("decode: {e}"))?;
    let raw = data
        .get("choices")
        .and_then(|c| c.get(0))
        .and_then(|c| c.get("message"))
        .and_then(|m| m.get("content"))
        .and_then(|c| c.as_str())
        .unwrap_or("");
    // Tolerant parse: extract the first `[...]` block so a model that wraps
    // the array in prose ("Here are the paraphrases: [...]") still works.
    let start = raw.find('[').ok_or("no JSON array in response")?;
    let end = raw.rfind(']').ok_or("no closing bracket")?;
    if end < start {
        return Err("malformed array bounds".into());
    }
    let slice = &raw[start..=end];
    let parsed: Vec<serde_json::Value> =
        serde_json::from_str(slice).map_err(|e| format!("parse: {e}"))?;
    Ok(parsed
        .into_iter()
        .filter_map(|v| v.as_str().map(str::to_string))
        .collect())
}

/// Wipe the per-process expansion cache. Test-only — `cargo test` runs many
/// expansion tests against different mock servers; without a clear, a hit
/// from a previous test would mask the new mock's responses.
#[cfg(any(test, feature = "kb"))]
pub async fn _clear_cache_for_tests() {
    let mut guard = cache().lock().await;
    *guard = LruCache::new(CACHE_CAP, Some(CACHE_TTL));
}
