//! Multi-turn query rewriter — port of `src/lib/rag/standalone-query.ts`.
//!
//! Takes the latest user query plus an ordered chat history of (role,
//! content) pairs and rewrites the query into a self-contained search
//! string. "tell me more about exclusions" becomes "exclusions for policy X"
//! using context from prior turns.
//!
//! Fail-soft contract:
//! - `cfg.standalone_query_enabled` is false → returns unchanged (TS parity)
//! - empty chat_history → returns the query unchanged (nothing to anchor against)
//! - query length ≥ 60 chars → returns unchanged (already self-contained)
//! - missing `OPENROUTER_API_KEY` → returns unchanged
//! - LLM call fails / returns empty → returns unchanged
//!
//! Cached for 5min, capacity 256, keyed on `(query, hash(history))` so the
//! same conversation re-played hits cache but different conversations
//! producing the same follow-up get different rewrites.

use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};
use std::sync::OnceLock;
use std::time::Duration;

use tokio::sync::Mutex;

use crate::kb::embed::cache::LruCache;
use crate::kb::{KbConfig, KbResult};

const TIMEOUT: Duration = Duration::from_secs(6);
const CACHE_CAP: usize = 256;
// 5min matches the TS source's cache TTL. Using `from_mins` keeps clippy
// (duration_suboptimal_units) happy without an arbitrary `5 * 60` literal.
const CACHE_TTL: Duration = Duration::from_mins(5);

/// Minimum chars below which we consider the query "likely needs rewriting".
/// Mirrors the TS source's `< 60` heuristic.
const SELF_CONTAINED_MIN: usize = 60;

fn cache() -> &'static Mutex<LruCache<String, String>> {
    static CACHE: OnceLock<Mutex<LruCache<String, String>>> = OnceLock::new();
    CACHE.get_or_init(|| Mutex::new(LruCache::new(CACHE_CAP, Some(CACHE_TTL))))
}

/// Rewrite `user_query` against `chat_history` into a standalone search query.
///
/// `chat_history` is an ordered list of `(role, content)` pairs — most recent
/// last. The latest user message (the query being rewritten) should NOT be
/// duplicated in chat_history; pass it once as `user_query` and the prior
/// turns separately.
///
/// Returns `Ok(query)` unchanged on every failure path — the result is always
/// a usable search string.
pub async fn rewrite_standalone(
    cfg: &KbConfig,
    user_query: &str,
    chat_history: &[(String, String)],
) -> KbResult<String> {
    let latest = user_query.trim();
    if latest.is_empty() {
        return Ok(String::new());
    }
    if chat_history.is_empty() {
        return Ok(latest.to_string());
    }
    // Opt-in feature gate — TS source guards the LLM call with
    // `process.env.KB_STANDALONE_QUERY_ENABLED !== "true"`. Without this,
    // the rewriter ships always-on, which diverges from the TS contract.
    if !cfg.standalone_query_enabled {
        return Ok(latest.to_string());
    }
    // Self-contained heuristic: long messages rarely need disambiguation.
    if latest.chars().count() >= SELF_CONTAINED_MIN {
        return Ok(latest.to_string());
    }

    let api_key = std::env::var("OPENROUTER_API_KEY").unwrap_or_default();
    if api_key.is_empty() {
        return Ok(latest.to_string());
    }

    // Take the last 6 turns, truncate each to 400 chars + collapse whitespace.
    let recent: Vec<&(String, String)> = chat_history
        .iter()
        .rev()
        .take(6)
        .collect::<Vec<_>>()
        .into_iter()
        .rev()
        .collect();
    let history: String = recent
        .iter()
        .map(|(role, content)| {
            let txt: String = content
                .chars()
                .take(400)
                .collect::<String>()
                .split_whitespace()
                .collect::<Vec<_>>()
                .join(" ");
            format!("{role}: {txt}")
        })
        .filter(|line| {
            // Drop empty-content lines so the model sees only real signal.
            // "role: " has nothing useful after the colon.
            line.split(':')
                .nth(1)
                .map_or(false, |after| !after.trim().is_empty())
        })
        .collect::<Vec<_>>()
        .join("\n");

    if history.is_empty() {
        return Ok(latest.to_string());
    }

    // Cache key: model + latest + a hash of the history. Hashing keeps the
    // key short even for long conversations and avoids storing the full
    // history in the cache map. The model name is included so swapping
    // `KB_QUERY_EXPANSION_MODEL` (which the rewriter also uses) does NOT
    // return rewrites generated by the old model.
    let mut hasher = DefaultHasher::new();
    history.hash(&mut hasher);
    let key = format!(
        "{}::{latest}::{:016x}",
        cfg.query_expansion_model,
        hasher.finish()
    );

    if let Some(hit) = cache().lock().await.get(&key) {
        return Ok(hit);
    }

    let prompt = format!(
        "You rewrite multi-turn chat questions into self-contained search queries for a knowledge base.\n\
\n\
Rewrite the user's LATEST question so it can be searched on its own, using context from the conversation. Rules:\n\
- Preserve the user's intent exactly. Do not add facts the user did not say.\n\
- Keep the rewrite concise (one sentence, ideally under 25 words).\n\
- If the latest question is already self-contained, return it unchanged.\n\
- Output ONLY the rewritten query. No quotes, no prose, no labels.\n\
\n\
Conversation:\n\
{history}\n\
\n\
Latest question: {latest}\n\
\n\
Rewritten query:"
    );

    let body = serde_json::json!({
        "model": cfg.query_expansion_model,
        "messages": [{ "role": "user", "content": prompt }],
        "max_tokens": 120,
        "temperature": 0.1,
    });

    match fetch_rewrite(&cfg.openrouter_chat_url, &api_key, &body).await {
        Ok(rewritten) if !rewritten.is_empty() => {
            cache().lock().await.put(key, rewritten.clone());
            Ok(rewritten)
        }
        Ok(_) => Ok(latest.to_string()),
        Err(e) => {
            tracing::warn!(
                target: "kb::retrieve::standalone_query",
                error = %e,
                "rewrite failed; using original query",
            );
            Ok(latest.to_string())
        }
    }
}

async fn fetch_rewrite(
    url: &str,
    api_key: &str,
    body: &serde_json::Value,
) -> Result<String, String> {
    let client = crate::config::build_runtime_proxy_client_with_timeouts(
        "kb.retrieve.standalone_query",
        TIMEOUT.as_secs(),
        10,
    );
    let resp = client
        .post(url)
        .bearer_auth(api_key)
        .json(body)
        .send()
        .await
        .map_err(|e| format!("send: {e}"))?;
    if !resp.status().is_success() {
        return Err(format!("standalone-query {}", resp.status().as_u16()));
    }
    let data: serde_json::Value = resp.json().await.map_err(|e| format!("decode: {e}"))?;
    let raw = data
        .get("choices")
        .and_then(|c| c.get(0))
        .and_then(|c| c.get("message"))
        .and_then(|m| m.get("content"))
        .and_then(|c| c.as_str())
        .unwrap_or("");
    // Strip surrounding quotes the model may add.
    let cleaned = raw
        .trim()
        .trim_matches(|c| c == '"' || c == '\'' || c == '`')
        .trim();
    Ok(cleaned.to_string())
}

#[cfg(any(test, feature = "kb"))]
pub async fn _clear_cache_for_tests() {
    let mut guard = cache().lock().await;
    *guard = LruCache::new(CACHE_CAP, Some(CACHE_TTL));
}
