//! Memory snapshot — export/import core memories as human-readable Markdown.
//!
//! **Atomic Soul Export**: dumps `MemoryCategory::Core` from SQLite into
//! `MEMORY_SNAPSHOT.md` so the agent's "soul" is always Git-visible.
//!
//! **Auto-Hydration**: if `brain.db` is missing but `MEMORY_SNAPSHOT.md` exists,
//! re-indexes all entries back into a fresh SQLite database.

use anyhow::Result;
use chrono::{Local, Utc};
use rusqlite::{params, Connection};
use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

/// Filename for the snapshot (lives at workspace root for Git visibility).
pub const SNAPSHOT_FILENAME: &str = "MEMORY_SNAPSHOT.md";

/// Header written at the top of every snapshot file.
const SNAPSHOT_HEADER: &str = "# 🧠 RantaiClaw Memory Snapshot\n\n\
    > Auto-generated by RantaiClaw. Do not edit manually unless you know what you're doing.\n\
    > This file is the \"soul\" of your agent — if `brain.db` is lost, start the agent\n\
    > in this workspace and it will auto-hydrate from this file.\n\n";

/// Export all `Core` memories from SQLite → `MEMORY_SNAPSHOT.md`.
///
/// Returns the number of entries exported.
pub fn export_snapshot(workspace_dir: &Path) -> Result<usize> {
    let db_path = workspace_dir.join("memory").join("brain.db");
    if !db_path.exists() {
        tracing::debug!("snapshot export skipped: brain.db does not exist");
        return Ok(0);
    }

    let conn = Connection::open(&db_path)?;
    conn.execute_batch("PRAGMA journal_mode = WAL; PRAGMA synchronous = NORMAL;")?;

    let mut stmt = conn.prepare(
        "SELECT key, content, category, created_at, updated_at
         FROM memories
         WHERE category = 'core'
         ORDER BY updated_at DESC",
    )?;

    let rows: Vec<(String, String, String, String, String)> = stmt
        .query_map([], |row| {
            Ok((
                row.get(0)?,
                row.get(1)?,
                row.get(2)?,
                row.get(3)?,
                row.get(4)?,
            ))
        })?
        .filter_map(|r| r.ok())
        .collect();

    if rows.is_empty() {
        tracing::debug!("snapshot export: no core memories to export");
        return Ok(0);
    }

    let mut output = String::with_capacity(rows.len() * 200);
    output.push_str(SNAPSHOT_HEADER);

    let now = Local::now().format("%Y-%m-%d %H:%M:%S").to_string();
    write!(output, "**Last exported:** {now}\n\n").unwrap();
    write!(output, "**Total core memories:** {}\n\n---\n\n", rows.len()).unwrap();

    for (key, content, _category, created_at, updated_at) in &rows {
        write!(output, "### 🔑 `{key}`\n\n").unwrap();
        write!(output, "{content}\n\n").unwrap();
        write!(
            output,
            "*Created: {created_at} | Updated: {updated_at}*\n\n---\n\n"
        )
        .unwrap();
    }

    let snapshot_path = snapshot_path(workspace_dir);
    fs::write(&snapshot_path, output)?;

    tracing::info!(
        "📸 Memory snapshot exported: {} core memories → {}",
        rows.len(),
        snapshot_path.display()
    );

    Ok(rows.len())
}

/// Filename of the human-readable memory file injected into the system prompt.
pub const MEMORY_FILE: &str = "MEMORY.md";

/// Markers delimiting the region of `MEMORY.md` the runtime owns.
const PROJECTION_BEGIN: &str = "<!-- rantaiclaw:memory:begin -->";
const PROJECTION_END: &str = "<!-- rantaiclaw:memory:end -->";

/// Ceiling on the generated block.
///
/// The whole file is injected into the system prompt every session, so an
/// unbounded projection is a silent per-session token cost that grows with the
/// database.
pub const PROJECTION_MAX_CHARS: usize = 4_000;

/// Render core memories into the delimited block of `MEMORY.md`.
///
/// `brain.db` is authoritative; this file is its projection. The prompt already
/// injects `MEMORY.md`, but on the sqlite backend nothing ever wrote it — so the
/// tier guaranteed to reach the model held only scaffold prose while everything
/// the agent learned went somewhere the prompt never reads.
///
/// One direction only. Content outside the markers is human-authored and is
/// preserved byte-for-byte; content inside is generated and is replaced. A
/// bidirectional sync would need conflict rules and a way to tell a hand edit
/// from a stale render, which is not worth it when "facts through the agent,
/// prose by hand" is a clear enough split.
///
/// Returns the number of entries projected.
pub fn project_core_memories(workspace_dir: &Path) -> Result<usize> {
    let db_path = workspace_dir.join("memory").join("brain.db");
    if !db_path.exists() {
        return Ok(0);
    }

    let conn = Connection::open(&db_path)?;
    let mut stmt = conn.prepare(
        "SELECT key, content FROM memories
         WHERE category = 'core'
         ORDER BY updated_at DESC",
    )?;
    let rows: Vec<(String, String)> = stmt
        .query_map([], |row| Ok((row.get(0)?, row.get(1)?)))?
        .filter_map(std::result::Result::ok)
        .collect();

    let (body, projected, omitted) = render_projection(&rows);
    let block = format!(
        "{PROJECTION_BEGIN}\n\
         <!-- Generated from core memory. Edits inside this block are overwritten; \
         write prose outside it. -->\n\
         {body}{}{PROJECTION_END}",
        if omitted > 0 {
            format!(
                "_… {omitted} more core memor{} not shown._\n",
                if omitted == 1 { "y" } else { "ies" }
            )
        } else {
            String::new()
        }
    );

    let path = workspace_dir.join(MEMORY_FILE);
    let existing = fs::read_to_string(&path).unwrap_or_default();
    fs::write(&path, splice_block(&existing, &block))?;

    Ok(projected)
}

/// Render entries as list lines, stopping at the character ceiling.
///
/// Returns the body, how many entries it holds, and how many were left out.
fn render_projection(rows: &[(String, String)]) -> (String, usize, usize) {
    let mut body = String::new();
    let mut projected = 0_usize;

    for (key, content) in rows {
        let line = format!("- {key}: {}\n", content.replace('\n', " "));
        if body.chars().count() + line.chars().count() > PROJECTION_MAX_CHARS {
            break;
        }
        body.push_str(&line);
        projected += 1;
    }

    (body, projected, rows.len() - projected)
}

/// Replace the delimited block, or append one, leaving the rest untouched.
fn splice_block(existing: &str, block: &str) -> String {
    match (
        existing.find(PROJECTION_BEGIN),
        existing.find(PROJECTION_END),
    ) {
        (Some(start), Some(end)) if end > start => {
            let mut out = String::with_capacity(existing.len() + block.len());
            out.push_str(&existing[..start]);
            out.push_str(block);
            out.push_str(&existing[end + PROJECTION_END.len()..]);
            out
        }
        // No usable block: append one, keeping whatever is already there. A
        // half-written block from an interrupted run falls here too — appending
        // is recoverable, rewriting someone's file is not.
        _ => {
            let mut out = existing.to_string();
            if !out.is_empty() && !out.ends_with('\n') {
                out.push('\n');
            }
            if !out.is_empty() {
                out.push('\n');
            }
            out.push_str(block);
            out.push('\n');
            out
        }
    }
}

/// Import memories from `MEMORY_SNAPSHOT.md` into SQLite.
///
/// Called during cold-boot when `brain.db` doesn't exist but the snapshot does.
/// Returns the number of entries hydrated.
pub fn hydrate_from_snapshot(workspace_dir: &Path) -> Result<usize> {
    let snapshot = snapshot_path(workspace_dir);
    if !snapshot.exists() {
        return Ok(0);
    }

    let content = fs::read_to_string(&snapshot)?;
    let entries = parse_snapshot(&content);

    if entries.is_empty() {
        return Ok(0);
    }

    // Ensure the memory directory exists
    let db_dir = workspace_dir.join("memory");
    fs::create_dir_all(&db_dir)?;

    let db_path = db_dir.join("brain.db");
    let conn = Connection::open(&db_path)?;
    conn.execute_batch("PRAGMA journal_mode = WAL; PRAGMA synchronous = NORMAL;")?;

    // Use the backend's own schema rather than a second declaration of it. A
    // local copy drifts: the previous one omitted `embedding_cache.accessed_at`,
    // so the index `SqliteMemory::init_schema` builds on that column failed and
    // the hydrated database could not be opened at all.
    super::sqlite::SqliteMemory::init_schema(&conn)?;

    // UTC, matching what the backend writes — hygiene compares these as strings.
    let now = Utc::now().to_rfc3339();
    let mut hydrated = 0;

    for (key, content) in &entries {
        let id = uuid::Uuid::new_v4().to_string();
        let result = conn.execute(
            "INSERT OR IGNORE INTO memories (id, key, content, category, created_at, updated_at)
             VALUES (?1, ?2, ?3, 'core', ?4, ?5)",
            params![id, key, content, now, now],
        );

        match result {
            Ok(changed) if changed > 0 => {
                // FTS5 is populated by the `memories_ai` trigger that
                // `init_schema` installs — inserting here too would leave an
                // orphan index row with no matching `memories` rowid.
                hydrated += 1;
            }
            Ok(_) => {
                tracing::debug!("hydrate: key '{key}' already exists, skipping");
            }
            Err(e) => {
                tracing::warn!("hydrate: failed to insert key '{key}': {e}");
            }
        }
    }

    tracing::info!(
        "🧬 Memory hydration complete: {} entries restored from {}",
        hydrated,
        snapshot.display()
    );

    Ok(hydrated)
}

/// Check if we should auto-hydrate on startup.
///
/// Returns `true` if:
/// 1. `brain.db` does NOT exist (or is empty)
/// 2. `MEMORY_SNAPSHOT.md` DOES exist
pub fn should_hydrate(workspace_dir: &Path) -> bool {
    let db_path = workspace_dir.join("memory").join("brain.db");
    let snapshot = snapshot_path(workspace_dir);

    let db_missing_or_empty = if db_path.exists() {
        // DB exists but might be empty (freshly created)
        fs::metadata(&db_path)
            .map(|m| m.len() < 4096) // SQLite header is ~4096 bytes minimum
            .unwrap_or(true)
    } else {
        true
    };

    db_missing_or_empty && snapshot.exists()
}

/// Path to the snapshot file.
fn snapshot_path(workspace_dir: &Path) -> PathBuf {
    workspace_dir.join(SNAPSHOT_FILENAME)
}

/// Parse the structured markdown snapshot back into (key, content) pairs.
fn parse_snapshot(input: &str) -> Vec<(String, String)> {
    let mut entries = Vec::new();
    let mut current_key: Option<String> = None;
    let mut current_content = String::new();

    for line in input.lines() {
        let trimmed = line.trim();

        // Match: ### 🔑 `key_name`
        if trimmed.starts_with("### 🔑 `") && trimmed.ends_with('`') {
            // Save previous entry
            if let Some(key) = current_key.take() {
                let content = current_content.trim().to_string();
                if !content.is_empty() {
                    entries.push((key, content));
                }
            }

            // Extract new key
            let key = trimmed
                .strip_prefix("### 🔑 `")
                .and_then(|s| s.strip_suffix('`'))
                .unwrap_or("")
                .to_string();

            if !key.is_empty() {
                current_key = Some(key);
                current_content = String::new();
            }
        } else if current_key.is_some() {
            // Skip metadata lines and separators
            if trimmed.starts_with("*Created:") || trimmed == "---" {
                continue;
            }
            // Accumulate content
            if !current_content.is_empty() || !trimmed.is_empty() {
                if !current_content.is_empty() {
                    current_content.push('\n');
                }
                current_content.push_str(line);
            }
        }
    }

    // Don't forget the last entry
    if let Some(key) = current_key {
        let content = current_content.trim().to_string();
        if !content.is_empty() {
            entries.push((key, content));
        }
    }

    entries
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::memory::traits::Memory;
    use tempfile::TempDir;

    #[test]
    fn parse_snapshot_basic() {
        let input = r#"# 🧠 RantaiClaw Memory Snapshot

> Auto-generated by RantaiClaw.

**Last exported:** 2025-01-15 14:30:00

**Total core memories:** 2

---

### 🔑 `identity`

I am RantaiClaw, a self-preserving AI agent.

*Created: 2025-01-15 | Updated: 2025-01-15*

---

### 🔑 `preference_lang`

The user prefers Rust for systems programming.

*Created: 2025-01-14 | Updated: 2025-01-15*

---
"#;

        let entries = parse_snapshot(input);
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0].0, "identity");
        assert!(entries[0].1.contains("self-preserving"));
        assert_eq!(entries[1].0, "preference_lang");
        assert!(entries[1].1.contains("Rust"));
    }

    #[test]
    fn parse_snapshot_empty() {
        let input = "# 🧠 RantaiClaw Memory Snapshot\n\n> Nothing here.\n";
        let entries = parse_snapshot(input);
        assert!(entries.is_empty());
    }

    #[test]
    fn parse_snapshot_multiline_content() {
        let input = r#"### 🔑 `rules`

Rule 1: Always be helpful.
Rule 2: Never lie.
Rule 3: Protect the user.

*Created: 2025-01-15 | Updated: 2025-01-15*

---
"#;

        let entries = parse_snapshot(input);
        assert_eq!(entries.len(), 1);
        assert!(entries[0].1.contains("Rule 1"));
        assert!(entries[0].1.contains("Rule 3"));
    }

    #[test]
    fn export_no_db_returns_zero() {
        let tmp = TempDir::new().unwrap();
        let count = export_snapshot(tmp.path()).unwrap();
        assert_eq!(count, 0);
    }

    #[test]
    fn export_and_hydrate_roundtrip() {
        let tmp = TempDir::new().unwrap();
        let workspace = tmp.path();

        // Create a brain.db manually with some core memories
        let db_dir = workspace.join("memory");
        fs::create_dir_all(&db_dir).unwrap();
        let db_path = db_dir.join("brain.db");

        let conn = Connection::open(&db_path).unwrap();
        conn.execute_batch(
            "PRAGMA journal_mode = WAL;
             CREATE TABLE IF NOT EXISTS memories (
                id TEXT PRIMARY KEY,
                key TEXT NOT NULL UNIQUE,
                content TEXT NOT NULL,
                category TEXT NOT NULL DEFAULT 'core',
                embedding BLOB,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
             );
             CREATE INDEX IF NOT EXISTS idx_mem_key ON memories(key);",
        )
        .unwrap();

        let now = Local::now().to_rfc3339();
        conn.execute(
            "INSERT INTO memories (id, key, content, category, created_at, updated_at)
             VALUES ('id1', 'identity', 'I am a test agent', 'core', ?1, ?2)",
            params![now, now],
        )
        .unwrap();
        conn.execute(
            "INSERT INTO memories (id, key, content, category, created_at, updated_at)
             VALUES ('id2', 'preference', 'User likes Rust', 'core', ?1, ?2)",
            params![now, now],
        )
        .unwrap();
        // Non-core entry (should NOT be exported)
        conn.execute(
            "INSERT INTO memories (id, key, content, category, created_at, updated_at)
             VALUES ('id3', 'conv1', 'Random convo', 'conversation', ?1, ?2)",
            params![now, now],
        )
        .unwrap();
        drop(conn);

        // Export snapshot
        let exported = export_snapshot(workspace).unwrap();
        assert_eq!(exported, 2, "Should export only core memories");

        // Verify the file exists and is readable
        let snapshot = workspace.join(SNAPSHOT_FILENAME);
        assert!(snapshot.exists());
        let content = fs::read_to_string(&snapshot).unwrap();
        assert!(content.contains("identity"));
        assert!(content.contains("I am a test agent"));
        assert!(content.contains("preference"));
        assert!(!content.contains("Random convo"));

        // Simulate catastrophic failure: delete brain.db
        fs::remove_file(&db_path).unwrap();
        assert!(!db_path.exists());

        // Verify should_hydrate detects the scenario
        assert!(should_hydrate(workspace));

        // Hydrate from snapshot
        let hydrated = hydrate_from_snapshot(workspace).unwrap();
        assert_eq!(hydrated, 2, "Should hydrate both core memories");

        // Verify brain.db was recreated
        assert!(db_path.exists());

        // Verify the data is actually in the new database
        let conn = Connection::open(&db_path).unwrap();
        let count: i64 = conn
            .query_row("SELECT COUNT(*) FROM memories", [], |row| row.get(0))
            .unwrap();
        assert_eq!(count, 2);

        let identity: String = conn
            .query_row(
                "SELECT content FROM memories WHERE key = 'identity'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(identity, "I am a test agent");
    }

    #[test]
    fn should_hydrate_only_when_needed() {
        let tmp = TempDir::new().unwrap();
        let workspace = tmp.path();

        // No DB, no snapshot → false
        assert!(!should_hydrate(workspace));

        // Create snapshot but no DB → true
        let snapshot = workspace.join(SNAPSHOT_FILENAME);
        fs::write(&snapshot, "### 🔑 `test`\n\nHello\n").unwrap();
        assert!(should_hydrate(workspace));

        // Create a real DB → false
        let db_dir = workspace.join("memory");
        fs::create_dir_all(&db_dir).unwrap();
        let db_path = db_dir.join("brain.db");
        let conn = Connection::open(&db_path).unwrap();
        conn.execute_batch(
            "CREATE TABLE IF NOT EXISTS memories (
                id TEXT PRIMARY KEY,
                key TEXT NOT NULL UNIQUE,
                content TEXT NOT NULL,
                category TEXT NOT NULL DEFAULT 'core',
                embedding BLOB,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
             );
             INSERT INTO memories VALUES('x','x','x','core',NULL,'2025-01-01','2025-01-01');",
        )
        .unwrap();
        drop(conn);
        assert!(!should_hydrate(workspace));
    }

    #[test]
    fn hydrate_no_snapshot_returns_zero() {
        let tmp = TempDir::new().unwrap();
        let count = hydrate_from_snapshot(tmp.path()).unwrap();
        assert_eq!(count, 0);
    }

    // ── MEMORY.md projection ──────────────────────────────────────

    async fn workspace_with_core(entries: &[(&str, &str)]) -> TempDir {
        let tmp = TempDir::new().unwrap();
        let mem = crate::memory::SqliteMemory::new(tmp.path()).unwrap();
        for (k, c) in entries {
            mem.store(k, c, crate::memory::MemoryCategory::Core, None)
                .await
                .unwrap();
        }
        tmp
    }

    fn memory_md(dir: &Path) -> String {
        fs::read_to_string(dir.join(MEMORY_FILE)).unwrap_or_default()
    }

    #[tokio::test]
    async fn projection_writes_core_memories_into_the_block() {
        let tmp = workspace_with_core(&[("user_lang", "prefers Bahasa Indonesia")]).await;

        let n = project_core_memories(tmp.path()).unwrap();
        assert_eq!(n, 1);

        let out = memory_md(tmp.path());
        assert!(out.contains(PROJECTION_BEGIN));
        assert!(out.contains("- user_lang: prefers Bahasa Indonesia"));
        assert!(out.contains(PROJECTION_END));
    }

    /// The wizard scaffolds this file with guidance prose, and operators write
    /// their own notes in it. Projection owns the marked block and nothing else —
    /// this is what makes the change safe to ship to an existing workspace.
    #[tokio::test]
    async fn projection_preserves_content_outside_the_markers() {
        let tmp = workspace_with_core(&[("fact", "value")]).await;
        let path = tmp.path().join(MEMORY_FILE);
        fs::write(
            &path,
            format!(
                "# Long-Term Memory\n\nHand-written guidance from the wizard.\n\n\
                 {PROJECTION_BEGIN}\n- stale: old\n{PROJECTION_END}\n\n\
                 ## Operator notes\n\nDo not delete me.\n"
            ),
        )
        .unwrap();

        project_core_memories(tmp.path()).unwrap();

        let out = memory_md(tmp.path());
        assert!(out.contains("Hand-written guidance from the wizard."));
        assert!(out.contains("## Operator notes"));
        assert!(out.contains("Do not delete me."));
        assert!(out.contains("- fact: value"));
        assert!(!out.contains("- stale: old"), "block was not replaced");
    }

    #[tokio::test]
    async fn projection_replaces_a_previous_block_rather_than_appending() {
        let tmp = workspace_with_core(&[("k", "v")]).await;

        project_core_memories(tmp.path()).unwrap();
        project_core_memories(tmp.path()).unwrap();

        let out = memory_md(tmp.path());
        assert_eq!(
            out.matches(PROJECTION_BEGIN).count(),
            1,
            "regenerating stacked a second block:\n{out}"
        );
    }

    #[tokio::test]
    async fn projection_appends_a_block_to_a_file_without_markers() {
        let tmp = workspace_with_core(&[("k", "v")]).await;
        fs::write(
            tmp.path().join(MEMORY_FILE),
            "# Long-Term Memory\n\nJust prose, no markers.\n",
        )
        .unwrap();

        project_core_memories(tmp.path()).unwrap();

        let out = memory_md(tmp.path());
        assert!(out.contains("Just prose, no markers."));
        assert!(out.contains("- k: v"));
    }

    #[tokio::test]
    async fn projection_excludes_non_core_categories() {
        let tmp = TempDir::new().unwrap();
        let mem = crate::memory::SqliteMemory::new(tmp.path()).unwrap();
        mem.store(
            "core_one",
            "durable",
            crate::memory::MemoryCategory::Core,
            None,
        )
        .await
        .unwrap();
        mem.store(
            "chatter",
            "ephemeral",
            crate::memory::MemoryCategory::Conversation,
            None,
        )
        .await
        .unwrap();
        drop(mem);

        project_core_memories(tmp.path()).unwrap();

        let out = memory_md(tmp.path());
        assert!(out.contains("- core_one: durable"));
        assert!(!out.contains("chatter"));
    }

    /// The whole file goes into the system prompt every session, so the block
    /// has to be bounded or the token cost grows with the database.
    #[tokio::test]
    async fn projection_is_bounded() {
        let big = "x".repeat(500);
        let entries: Vec<(String, String)> =
            (0..50).map(|i| (format!("k{i}"), big.clone())).collect();
        let borrowed: Vec<(&str, &str)> = entries
            .iter()
            .map(|(k, c)| (k.as_str(), c.as_str()))
            .collect();
        let tmp = workspace_with_core(&borrowed).await;

        let projected = project_core_memories(tmp.path()).unwrap();

        let out = memory_md(tmp.path());
        assert!(projected < 50, "expected some entries to be omitted");
        assert!(
            out.chars().count() < PROJECTION_MAX_CHARS + 500,
            "block exceeded its ceiling: {} chars",
            out.chars().count()
        );
        assert!(out.contains("not shown"), "omission must be stated:\n{out}");
    }

    #[tokio::test]
    async fn projection_creates_the_file_when_absent() {
        let tmp = workspace_with_core(&[("k", "v")]).await;
        assert!(!tmp.path().join(MEMORY_FILE).exists());

        project_core_memories(tmp.path()).unwrap();

        assert!(tmp.path().join(MEMORY_FILE).exists());
    }

    #[test]
    fn projection_without_a_database_is_a_no_op() {
        let tmp = TempDir::new().unwrap();
        assert_eq!(project_core_memories(tmp.path()).unwrap(), 0);
        assert!(!tmp.path().join(MEMORY_FILE).exists());
    }

    /// Write a snapshot holding one core memory and hydrate it.
    fn hydrated_workspace() -> TempDir {
        let tmp = TempDir::new().unwrap();
        fs::write(
            tmp.path().join(SNAPSHOT_FILENAME),
            "### 🔑 `preference_lang`\n\nThe operator prefers Rust.\n\n---\n",
        )
        .unwrap();
        let count = hydrate_from_snapshot(tmp.path()).unwrap();
        assert_eq!(count, 1, "snapshot entry should hydrate");
        tmp
    }

    /// Hydration used to declare its own schema, which drifted from the
    /// backend's: it omitted `embedding_cache.accessed_at`, so the index
    /// `init_schema` builds on that column failed and the hydrated database
    /// could not be opened at all.
    #[tokio::test]
    async fn hydrated_database_opens_with_sqlite_memory() {
        let tmp = hydrated_workspace();
        crate::memory::SqliteMemory::new(tmp.path())
            .expect("a hydrated database must be openable by the backend");
    }

    #[tokio::test]
    async fn hydrated_entries_are_recallable() {
        let tmp = hydrated_workspace();
        let mem = crate::memory::SqliteMemory::new(tmp.path()).unwrap();
        let hits = mem.recall("Rust", 10, None).await.unwrap();
        assert_eq!(hits.len(), 1, "hydrated entry should be searchable");
        assert_eq!(hits[0].key, "preference_lang");
    }

    /// FTS5 is populated by the `memories_ai` trigger. Hydration must not also
    /// insert by hand: a manual insert into an external-content table takes a
    /// fresh rowid with no matching `memories` row, leaving a stray index entry.
    ///
    /// Asserted against the index itself, not through `recall` — `recall` joins
    /// on `m.rowid = f.rowid` and would silently drop the stray row, hiding the
    /// defect.
    #[test]
    fn hydrate_leaves_no_orphan_fts_rows() {
        let tmp = hydrated_workspace();
        let conn = Connection::open(tmp.path().join("memory").join("brain.db")).unwrap();

        let indexed: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM memories_fts WHERE memories_fts MATCH 'prefers'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        let joined: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM memories_fts f \
                 JOIN memories m ON m.rowid = f.rowid \
                 WHERE memories_fts MATCH 'prefers'",
                [],
                |row| row.get(0),
            )
            .unwrap();

        assert_eq!(indexed, 1, "expected one FTS index entry, got {indexed}");
        assert_eq!(
            indexed, joined,
            "every FTS row must map to a memories row; {} indexed vs {} joined",
            indexed, joined
        );
    }
}
