#!/usr/bin/env python3
"""Render an RGBA PNG into a Rust source snippet for the ratatui splash.

For each (row, row+1) pair we emit a `▀` (upper half block) per column:
  - foreground colour = upper pixel
  - background colour = lower pixel
  - fully-transparent pixels collapse to "no colour" so the splash
    blends with whatever the terminal background is.

Output is a Rust slice of pixel tuples — the splash code keeps that
as `MASCOT_PIXELS` and renders each row as a `Line` of styled spans.

Usage:
    python3 tools/render_mascot.py <src.png> [width] [height_pixels]

Example (regenerate the bundled crab at 32 cols × 16 rows):
    venv/bin/python tools/render_mascot.py \\
        src/tui/assets/mascot_source.png 32 32 \\
        > src/tui/assets/mascot_pixels.rs

Requires Pillow (e.g. `python3 -m venv venv && venv/bin/pip install Pillow`).
"""

import sys
from PIL import Image

SRC = sys.argv[1]
WIDTH = int(sys.argv[2]) if len(sys.argv) > 2 else 24
TARGET_H_PIXELS = int(sys.argv[3]) if len(sys.argv) > 3 else 24  # in raster rows

im = Image.open(SRC).convert("RGBA")

# Auto-crop transparent/near-white border so the crab fills the cell grid.
bbox = im.getbbox()
if bbox:
    im = im.crop(bbox)
    # Trim near-white background rows/cols (logo is on white canvas).
    px = im.load()
    w, h = im.size
    def row_nonbg(y):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a > 16 and (r < 240 or g < 240 or b < 240):
                return True
        return False
    def col_nonbg(x):
        for y in range(h):
            r, g, b, a = px[x, y]
            if a > 16 and (r < 240 or g < 240 or b < 240):
                return True
        return False
    top = next((y for y in range(h) if row_nonbg(y)), 0)
    bot = next((y for y in range(h - 1, -1, -1) if row_nonbg(y)), h - 1)
    left = next((x for x in range(w) if col_nonbg(x)), 0)
    right = next((x for x in range(w - 1, -1, -1) if col_nonbg(x)), w - 1)
    im = im.crop((left, top, right + 1, bot + 1))

# Resize. Pixel aspect ≈ square; a terminal cell ≈ 2x tall as wide. We render
# two raster rows per char row via half blocks, so target pixel height = 2 *
# char rows. Width is exactly char columns.
target_w = WIDTH
target_h = TARGET_H_PIXELS  # must be even
if target_h % 2 != 0:
    target_h += 1
im = im.resize((target_w, target_h), Image.LANCZOS)

# Compose against a white background since the asset was designed on one.
bg = Image.new("RGBA", im.size, (255, 255, 255, 255))
flat = Image.alpha_composite(bg, im).convert("RGB")
px = flat.load()
alpha = im.split()[3].load()  # to know which cells are transparent

def is_transparent(x, y):
    return alpha[x, y] < 24

print("// Generated by tools/render_mascot.py — do not edit by hand.")
print(f"// Source: {SRC}")
print(f"// Grid: {target_w} cols × {target_h // 2} rows (half-block, {target_h} px tall)")
print()
print(
    "pub const MASCOT_PIXELS: &[&[(u8, u8, u8, bool, u8, u8, u8, bool)]] = &["
)
for y in range(0, target_h, 2):
    cells = []
    for x in range(target_w):
        ur, ug, ub = px[x, y]
        lr, lg, lb = px[x, y + 1]
        u_trans = is_transparent(x, y)
        l_trans = is_transparent(x, y + 1)
        # 1 = transparent (no colour applied) so the Rust side can skip it.
        cells.append(
            f"({ur},{ug},{ub},{'true' if u_trans else 'false'},"
            f"{lr},{lg},{lb},{'true' if l_trans else 'false'})"
        )
    print("    &[" + ",".join(cells) + "],")
print("];")
