//! Tests for the KB file-processor (`src/kb/file/`).
//!
//! Fixtures are generated on demand into `tests/fixtures/` so we don't
//! commit transient binaries. Office fixtures for the `kb-office`-gated
//! tests live alongside (also generated where possible — docx via
//! `docx-rs`'s own writer; xlsx ships as a tiny committed fixture because
//! `calamine` is reader-only).

use std::path::{Path, PathBuf};

use rantaiclaw::kb::file::{
    self, detect_file_type, is_supported_file, process_file, scan_directory, supported_extensions,
    ProcessingOptions, SupportedFileType,
};
use rantaiclaw::kb::{KbConfig, KbError};

// ----- shared test config -------------------------------------------------

/// Mirror of the `vision_cfg` helper from `extract_test.rs`. Inlined here
/// to keep the two test files self-contained (each integration test file
/// compiles independently when run with `--test`).
fn make_kb_cfg(vision_base_url: String) -> KbConfig {
    KbConfig {
        extract_primary: "unpdf".into(),
        extract_fallback: "unpdf".into(),
        extract_smart_fallback: "unpdf".into(),
        embedding_model: "rantaiclaw_test_model_a".into(),
        embedding_dim: 4,
        default_max_chunks: 8,
        rerank_enabled: false,
        rerank_provider: String::new(),
        rerank_model: "rantaiclaw_test_model_a".into(),
        rerank_initial_k: 20,
        rerank_final_k: 5,
        hybrid_bm25_enabled: true,
        contextual_retrieval_enabled: false,
        contextual_retrieval_model: "rantaiclaw_test_model_a".into(),
        query_expansion_enabled: false,
        query_expansion_model: "rantaiclaw_test_model_a".into(),
        query_expansion_paraphrases: 3,
        extract_vision_base_url: vision_base_url,
        extract_vision_api_key: "rantaiclaw_test_key".into(),
        extract_mineru_base_url: String::new(),
        embedding_base_url: String::new(),
        embedding_api_key: String::new(),
        embed_batch_size: 100,
        embed_concurrency: 2,
        query_embed_cache_size: 8,
        query_embed_cache_ttl_ms: 60_000,
    }
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from("tests/fixtures")
}

/// Reuses the cached sample PDF generated by `extract_test.rs` if present;
/// otherwise builds one inline. Keeps this test file independent of the
/// extract test binary's helpers.
fn ensure_sample_pdf() -> PathBuf {
    let path = fixtures_dir().join("sample-text.pdf");
    if path.exists() {
        return path;
    }
    std::fs::create_dir_all(fixtures_dir()).expect("create fixtures dir");
    let bytes = build_minimal_pdf("RantaiClawSample Hello World");
    std::fs::write(&path, bytes).expect("write sample-text.pdf");
    path
}

fn build_minimal_pdf(text: &str) -> Vec<u8> {
    use lopdf::content::{Content, Operation};
    use lopdf::{dictionary, Document, Object, Stream};

    let mut doc = Document::with_version("1.5");
    let pages_id = doc.new_object_id();
    let font_id = doc.add_object(dictionary! {
        "Type" => "Font",
        "Subtype" => "Type1",
        "BaseFont" => "Helvetica",
    });
    let resources_id = doc.add_object(dictionary! {
        "Font" => dictionary! { "F1" => font_id },
    });
    let content = Content {
        operations: vec![
            Operation::new("BT", vec![]),
            Operation::new("Tf", vec!["F1".into(), 24.into()]),
            Operation::new("Td", vec![100.into(), 600.into()]),
            Operation::new("Tj", vec![Object::string_literal(text)]),
            Operation::new("ET", vec![]),
        ],
    };
    let content_id = doc.add_object(Stream::new(
        dictionary! {},
        content.encode().expect("encode pdf content"),
    ));
    let page_id = doc.add_object(dictionary! {
        "Type" => "Page",
        "Parent" => pages_id,
        "Contents" => content_id,
    });
    doc.objects.insert(
        pages_id,
        Object::Dictionary(dictionary! {
            "Type" => "Pages",
            "Kids" => vec![page_id.into()],
            "Count" => 1_i64,
            "Resources" => resources_id,
            "MediaBox" => vec![0.into(), 0.into(), 595.into(), 842.into()],
        }),
    );
    let catalog_id = doc.add_object(dictionary! {
        "Type" => "Catalog",
        "Pages" => pages_id,
    });
    doc.trailer.set("Root", catalog_id);
    doc.compress();
    let mut buf: Vec<u8> = Vec::new();
    doc.save_to(&mut buf).expect("save pdf");
    buf
}

/// Minimal valid 1x1 PNG. Generated programmatically (zero deps, ~70 bytes).
/// Used to assert the data-URL encoding path, not to verify any actual
/// vision-model output.
fn tiny_png_bytes() -> Vec<u8> {
    // 1x1 transparent PNG, hand-coded. Crc32 values are precomputed.
    // Sourced from the smallest PNG known to validate (8-bit gray, IDAT
    // contains a single deflate-compressed zero byte).
    vec![
        0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, // signature
        0x00, 0x00, 0x00, 0x0D, // IHDR length
        0x49, 0x48, 0x44, 0x52, // "IHDR"
        0x00, 0x00, 0x00, 0x01, // width=1
        0x00, 0x00, 0x00, 0x01, // height=1
        0x08, 0x00, 0x00, 0x00, 0x00, // 8-bit grayscale, no interlace
        0x3B, 0x7E, 0x9B, 0x55, // IHDR CRC
        0x00, 0x00, 0x00, 0x0A, // IDAT length=10
        0x49, 0x44, 0x41, 0x54, // "IDAT"
        0x78, 0x9C, 0x63, 0x00, 0x01, 0x00, 0x00, 0x05, 0x00, 0x01, // deflate payload
        0x0D, 0x0A, 0x2D, 0xB4, // IDAT CRC
        0x00, 0x00, 0x00, 0x00, // IEND length=0
        0x49, 0x45, 0x4E, 0x44, // "IEND"
        0xAE, 0x42, 0x60, 0x82, // IEND CRC
    ]
}

// ----- task 6.1: detection + verbatim file types -------------------------

#[test]
fn detect_file_type_handles_all_known_extensions() {
    assert_eq!(
        detect_file_type(Path::new("doc.md")),
        Some(SupportedFileType::Markdown)
    );
    assert_eq!(
        detect_file_type(Path::new("paper.PDF")),
        Some(SupportedFileType::Pdf),
        "extension match must be case-insensitive"
    );
    assert_eq!(
        detect_file_type(Path::new("snap.png")),
        Some(SupportedFileType::Image)
    );
    assert_eq!(
        detect_file_type(Path::new("report.docx")),
        Some(SupportedFileType::Document)
    );
    assert_eq!(
        detect_file_type(Path::new("main.rs")),
        Some(SupportedFileType::Text)
    );
    assert!(detect_file_type(Path::new("foo.unknownext")).is_none());
    assert!(detect_file_type(Path::new("Makefile")).is_none());
    assert!(is_supported_file(Path::new("notes.markdown")));
    assert!(!supported_extensions().is_empty());
}

#[tokio::test]
async fn process_markdown_returns_content_verbatim() {
    let cfg = make_kb_cfg("http://127.0.0.1:1/unused".into());
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("note.md");
    let body = "# rantaiclaw test\n\nbody line";
    std::fs::write(&path, body).unwrap();

    let processed = process_file(&cfg, &path, ProcessingOptions::default())
        .await
        .unwrap();
    assert_eq!(processed.content, body);
    assert_eq!(processed.file_type, SupportedFileType::Markdown);
    assert_eq!(processed.original_path, path);
}

#[tokio::test]
async fn process_text_returns_content_verbatim() {
    let cfg = make_kb_cfg("http://127.0.0.1:1/unused".into());
    let dir = tempfile::tempdir().unwrap();

    // .txt
    let txt = dir.path().join("notes.txt");
    std::fs::write(&txt, "rantaiclaw plain body\nsecond line").unwrap();
    let r = process_file(&cfg, &txt, ProcessingOptions::default())
        .await
        .unwrap();
    assert_eq!(r.content, "rantaiclaw plain body\nsecond line");
    assert_eq!(r.file_type, SupportedFileType::Text);

    // .csv
    let csv = dir.path().join("data.csv");
    std::fs::write(&csv, "a,b,c\n1,2,3\n").unwrap();
    let r2 = process_file(&cfg, &csv, ProcessingOptions::default())
        .await
        .unwrap();
    assert_eq!(r2.content, "a,b,c\n1,2,3\n");
    assert_eq!(r2.file_type, SupportedFileType::Text);
}

// ----- task 6.1: image vision call ---------------------------------------

#[tokio::test]
async fn process_image_makes_openrouter_vision_call() {
    use serde_json::json;
    use wiremock::matchers::{method, path};
    use wiremock::{Mock, MockServer, Request, ResponseTemplate};

    let server = MockServer::start().await;
    // Capture the request body for shape assertions after the call.
    let captured: std::sync::Arc<std::sync::Mutex<Option<serde_json::Value>>> =
        std::sync::Arc::new(std::sync::Mutex::new(None));
    let captured_clone = captured.clone();

    let body = json!({
        "choices": [{ "message": { "content": "## image description body" }}]
    });
    Mock::given(method("POST"))
        .and(path("/chat"))
        .respond_with(move |req: &Request| {
            let parsed: serde_json::Value =
                serde_json::from_slice(&req.body).expect("body must be JSON");
            *captured_clone.lock().unwrap() = Some(parsed);
            ResponseTemplate::new(200).set_body_json(body.clone())
        })
        .expect(1)
        .mount(&server)
        .await;

    let cfg = make_kb_cfg(format!("{}/chat", server.uri()));
    let dir = tempfile::tempdir().unwrap();
    let img = dir.path().join("rantaiclaw_snap.png");
    std::fs::write(&img, tiny_png_bytes()).unwrap();

    let r = process_file(&cfg, &img, ProcessingOptions::default())
        .await
        .unwrap();

    assert_eq!(r.file_type, SupportedFileType::Image);
    assert!(
        r.content.starts_with("[Image: rantaiclaw_snap.png]\n\n"),
        "wrapper line missing or wrong, got: {}",
        r.content
    );
    assert!(
        r.content.ends_with("## image description body"),
        "body must follow wrapper, got: {}",
        r.content
    );

    let captured = captured
        .lock()
        .unwrap()
        .clone()
        .expect("captured request body");
    // Walk down to the image_url content block.
    let messages = captured["messages"].as_array().expect("messages array");
    let content_blocks = messages[0]["content"]
        .as_array()
        .expect("content blocks array");
    let image_block = content_blocks
        .iter()
        .find(|b| b["type"] == "image_url")
        .expect("image_url block must be present");
    let url = image_block["image_url"]["url"]
        .as_str()
        .expect("image_url.url must be a string");
    assert!(
        url.starts_with("data:image/png;base64,"),
        "url must be a data: URL with image/png mime, got: {url}"
    );
}

// ----- task 6.1: pdf dispatch -------------------------------------------

#[tokio::test]
async fn process_pdf_dispatches_to_smart_router() {
    // Set the extractor pair to ("unpdf", "unpdf") so we never hit HTTP.
    // The smart sentinel itself is exercised by extract_test.rs; here we
    // just need to confirm process_file routes PDFs through the chain.
    let cfg = make_kb_cfg("http://127.0.0.1:1/unused".into());
    let pdf_path = ensure_sample_pdf();
    let r = process_file(&cfg, &pdf_path, ProcessingOptions::default())
        .await
        .unwrap();
    assert_eq!(r.file_type, SupportedFileType::Pdf);
    assert!(
        r.content.contains("RantaiClawSample"),
        "extractor output must surface the sample marker, got: {:?}",
        r.content
    );
}

// ----- task 6.1: error paths --------------------------------------------

#[tokio::test]
async fn process_file_errors_on_unsupported_extension() {
    let cfg = make_kb_cfg("http://127.0.0.1:1/unused".into());
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("unknown.xyz");
    std::fs::write(&path, b"contents").unwrap();
    let err = process_file(&cfg, &path, ProcessingOptions::default())
        .await
        .expect_err("unknown extension must fail");
    assert!(
        matches!(err, KbError::UnsupportedFileType(_)),
        "expected UnsupportedFileType, got: {err}"
    );
}

#[tokio::test]
async fn process_file_errors_on_missing_file() {
    let cfg = make_kb_cfg("http://127.0.0.1:1/unused".into());
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("does_not_exist.md");
    let err = process_file(&cfg, &path, ProcessingOptions::default())
        .await
        .expect_err("missing file must fail");
    assert!(
        matches!(err, KbError::NotFound(_)),
        "expected NotFound, got: {err}"
    );
}

#[tokio::test]
async fn process_pdf_with_ocr_pipeline_flag_returns_not_implemented_error() {
    // Guard: the Ollama OCR pipeline isn't ported yet, but the flag still
    // exists on `ProcessingOptions`. Asking for it must fail explicitly
    // (KISS + fail-fast — no silent fallback to vision-LLM).
    let cfg = make_kb_cfg("http://127.0.0.1:1/unused".into());
    let pdf_path = ensure_sample_pdf();
    let opts = ProcessingOptions {
        use_ocr_pipeline: true,
        ..Default::default()
    };
    let err = process_file(&cfg, &pdf_path, opts)
        .await
        .expect_err("ocr pipeline flag must surface NotImplemented");
    let msg = err.to_string();
    assert!(
        msg.contains("OCR pipeline not yet implemented"),
        "error must explain OCR pipeline isn't ported: {msg}"
    );
}

// ----- task 6.1: scan_directory -----------------------------------------

#[test]
fn scan_directory_finds_supported_files_recursively() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    let nested = root.join("nested");
    std::fs::create_dir(&nested).unwrap();

    let md = root.join("a.md");
    let pdf = nested.join("b.pdf");
    let bad = nested.join("c.unsupported");
    std::fs::write(&md, "x").unwrap();
    std::fs::write(&pdf, "x").unwrap();
    std::fs::write(&bad, "x").unwrap();

    let mut found = scan_directory(root);
    found.sort();
    let mut expected = vec![md.clone(), pdf.clone()];
    expected.sort();
    assert_eq!(found, expected, "scan must return md + pdf, not unsupported");
}

#[test]
fn scan_directory_returns_empty_for_missing_dir() {
    let dir = tempfile::tempdir().unwrap();
    let missing = dir.path().join("nope");
    assert!(file::scan_directory(&missing).is_empty());
}

// ----- task 6.2: office support (feature-gated) --------------------------

#[cfg(feature = "kb-office")]
mod office {
    use super::*;

    use docx_rs::{Docx, Paragraph, Run};

    fn build_docx_bytes(paragraphs: &[&str]) -> Vec<u8> {
        let mut doc = Docx::new();
        for body in paragraphs {
            doc = doc.add_paragraph(Paragraph::new().add_run(Run::new().add_text(*body)));
        }
        let xml = doc.build();
        let mut buf = std::io::Cursor::new(Vec::<u8>::new());
        docx_rs::zip(&mut buf, xml).expect("zip docx");
        buf.into_inner()
    }

    #[tokio::test]
    async fn process_office_docx_extracts_text() {
        let cfg = make_kb_cfg("http://127.0.0.1:1/unused".into());
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("rantaiclaw_doc.docx");
        let bytes = build_docx_bytes(&["First paragraph rantaiclaw.", "Second paragraph body."]);
        std::fs::write(&path, bytes).unwrap();

        let r = process_file(&cfg, &path, ProcessingOptions::default())
            .await
            .unwrap();
        assert_eq!(r.file_type, SupportedFileType::Document);
        assert!(
            r.content.contains("First paragraph rantaiclaw."),
            "first paragraph missing: {:?}",
            r.content
        );
        assert!(
            r.content.contains("Second paragraph body."),
            "second paragraph missing: {:?}",
            r.content
        );
    }

    /// Committed fixture: `tests/fixtures/sample.xlsx`. Hand-crafted to keep
    /// the integration self-contained; `calamine` is reader-only.
    fn ensure_xlsx_fixture() -> PathBuf {
        fixtures_dir().join("sample.xlsx")
    }

    #[tokio::test]
    async fn process_office_xlsx_extracts_sheet_content() {
        let cfg = make_kb_cfg("http://127.0.0.1:1/unused".into());
        let path = ensure_xlsx_fixture();
        assert!(
            path.exists(),
            "tests/fixtures/sample.xlsx must be committed for this test"
        );

        let r = process_file(&cfg, &path, ProcessingOptions::default())
            .await
            .unwrap();
        assert_eq!(r.file_type, SupportedFileType::Document);
        // Output convention: `## Sheet: <name>` headers + TSV rows.
        assert!(
            r.content.contains("## Sheet:"),
            "sheet header missing in xlsx output: {:?}",
            r.content
        );
        assert!(
            r.content.to_lowercase().contains("hello"),
            "expected fixture cell text 'hello' missing: {:?}",
            r.content
        );
    }

    #[tokio::test]
    async fn process_office_returns_error_for_unsupported_extension() {
        let cfg = make_kb_cfg("http://127.0.0.1:1/unused".into());
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("deck.pptx");
        // `.pptx` is in DOCUMENT_EXTENSIONS so the dispatcher routes here,
        // but office.rs returns UnsupportedFileType for pptx specifically.
        std::fs::write(&path, b"not a real pptx").unwrap();
        let err = process_file(&cfg, &path, ProcessingOptions::default())
            .await
            .expect_err("pptx must surface UnsupportedFileType");
        assert!(
            matches!(err, KbError::UnsupportedFileType(_)),
            "expected UnsupportedFileType, got: {err}"
        );
    }
}
